version: '3.4'
services:
  db:
    image: mysql:5.6
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'test'
    volumes:
      - my-db:/var/lib/mysql
      - ./home:/root/
volumes:
  my-db: